version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-library:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  test-library:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run tests
          command: npm run test
    # any other sort of tests could be added here 

  scan-library:
    # scanning
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: |
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
    # any other sort of scanning could be added here, also Sonarqube server could be integrated and used for code scanning

  publish-package:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish --access public
          environment:
            NPM_TOKEN: $NPM_TOKEN  # we need to ensure NPM_TOKEN is set in CircleCI environment variables

workflows:
  ui-internal-library:
    jobs:
      - build-library
      - test-library:
          requires:
            - build-library
      - scan-library:
          requires:
            - build-library
      - publish-package:
          requires:
            - test-library
            - scan-library
            